# Generated by Django 4.0.3 on 2022-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_api_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGenericApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
